name: CI Workflow Main - Grupo 3
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16
          
      - name: instalando o packpage
        run: npm install
      - name: Build para producao
        run: npm run build -- --prod
      - name: atualizar os artefatos
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
